#!/usr/bin/env node
/**
 * Auto-generate Next.js convention files
 * Runs after pnpm install
 */
const fs = require('fs');
const path = require('path');

const cwd = process.cwd();
const hasNextConfig = ['next.config.js', 'next.config.ts', 'next.config.mjs'].some(
  f => fs.existsSync(path.join(cwd, f))
);

if (!hasNextConfig) process.exit(0);

console.log('[AI-First] Setting up Next.js integration...');

const srcDir = path.join(cwd, 'src');

// 扫描 controller 文件
function scanControllers() {
  const controllerDir = path.join(srcDir, 'api/controller');
  if (!fs.existsSync(controllerDir)) return [];
  
  return fs.readdirSync(controllerDir)
    .filter(f => f.endsWith('.controller.ts') && f !== 'index.ts')
    .map(f => {
      const name = f.replace('.controller.ts', '');
      const className = name.split('-').map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('') + 'Controller';
      return { file: f.replace('.ts', ''), className };
    });
}

// 扫描 service 文件
function scanServices() {
  const serviceDir = path.join(srcDir, 'api/service');
  if (!fs.existsSync(serviceDir)) return [];
  
  return fs.readdirSync(serviceDir)
    .filter(f => f.endsWith('.service.ts') && f !== 'index.ts')
    .map(f => f.replace('.ts', ''));
}

// 扫描 mapper 文件
function scanMappers() {
  const mapperDir = path.join(srcDir, 'api/mapper');
  if (!fs.existsSync(mapperDir)) return [];
  
  return fs.readdirSync(mapperDir)
    .filter(f => f.endsWith('.mapper.ts') && f !== 'index.ts')
    .map(f => f.replace('.ts', ''));
}

// 生成 api route
const apiDir = path.join(srcDir, 'app/api/[...path]');
const routeFile = path.join(apiDir, 'route.ts');

const controllers = scanControllers();
const services = scanServices();
const mappers = scanMappers();

// 生成导入语句
let imports = `/**
 * Auto-generated by @ai-first/nextjs
 * DO NOT EDIT
 */
import 'reflect-metadata';
import { createApiRouter } from '@ai-first/nextjs';
`;

// 导入 mapper (先注册)
mappers.forEach(m => {
  imports += `import '@/api/mapper/${m}';\n`;
});

// 导入 service
services.forEach(s => {
  imports += `import '@/api/service/${s}';\n`;
});

// 导入 controller
controllers.forEach(c => {
  imports += `import { ${c.className} } from '@/api/controller/${c.file}';\n`;
});

// 生成路由
const controllerArray = controllers.map(c => c.className).join(', ');
imports += `
export const { GET, POST, PUT, DELETE, PATCH } = createApiRouter([${controllerArray}]);
`;

fs.mkdirSync(apiDir, { recursive: true });
fs.writeFileSync(routeFile, imports);
console.log('[AI-First] Generated: src/app/api/[...path]/route.ts');

// instrumentation.ts 不再需要了
const instrumentationFile = path.join(srcDir, 'instrumentation.ts');
if (fs.existsSync(instrumentationFile)) {
  fs.unlinkSync(instrumentationFile);
  console.log('[AI-First] Removed: src/instrumentation.ts (no longer needed)');
}

console.log('[AI-First] Setup complete!');
