/**
 * Next.js Plugin - Auto API Route Generation
 * 
 * 在 next.config.ts 中使用：
 * import { withAIFirst } from '@ai-first/nextjs';
 * export default withAIFirst({ controllerPath: './src/lib/controller' });
 */
import type { NextConfig } from 'next';
import fs from 'fs';
import path from 'path';

export interface AIFirstOptions {
  /** Controller 目录路径，默认 './src/lib/controller' */
  controllerPath?: string;
}

const API_ROUTE_TEMPLATE = `/**
 * Auto-generated by @ai-first/nextjs
 * DO NOT EDIT - This file is automatically managed
 */
import { createApiRouter } from '@ai-first/nextjs';
import * as controllers from '@/lib/controller';

export const { GET, POST, PUT, DELETE, PATCH } = createApiRouter(controllers);
`;

export function withAIFirst(options: AIFirstOptions = {}) {
  return (nextConfig: NextConfig): NextConfig => {
    const originalWebpack = nextConfig.webpack;
    
    return {
      ...nextConfig,
      webpack: (config, context) => {
        // 只在服务端构建时生成
        if (context.isServer && !context.dev) {
          generateApiRoute(options.controllerPath);
        }
        
        // 开发模式下也生成
        if (context.dev && context.isServer) {
          generateApiRoute(options.controllerPath);
        }
        
        if (originalWebpack) {
          return originalWebpack(config, context);
        }
        return config;
      },
    };
  };
}

function generateApiRoute(_controllerPath?: string) {
  const apiDir = path.join(process.cwd(), 'src/app/api/[...path]');
  const routeFile = path.join(apiDir, 'route.ts');
  
  // 创建目录
  if (!fs.existsSync(apiDir)) {
    fs.mkdirSync(apiDir, { recursive: true });
  }
  
  // 写入文件
  fs.writeFileSync(routeFile, API_ROUTE_TEMPLATE);
  console.log('[AI-First] Generated API route: src/app/api/[...path]/route.ts');
}

// 导出初始化函数，可在 instrumentation.ts 中使用
export function initApiRoutes(options: AIFirstOptions = {}) {
  generateApiRoute(options.controllerPath);
}
